# Generated by Django 3.2 on 2022-09-23 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_date',
            field=models.DateField(default=datetime.date(2022, 9, 24)),
        ),
    ]
